### PR TITLE
converting charts from kw to mw

### LINKED ISSUE #36: show power generated in MW instead of KW
The numbers are so high, that megawatts is easier to read and will save some visual space.

This change applies to the map legend, charts and tables

### LINKED ISSUE #54: change time series chart order to show largest on the bottom
Order from bottom should be: utility, small DG, large DG, community solar

Screenshot 2024-06-05 at 9 04 04 AM

### PR DESCRIPTION
**Pull request by derekeder**
## Overview

* Changes order of time series chart to show largest on bottom. Closes #54 
* Changes data and chart format on about page to use megawatts instead of kilowatts. Closes #36 

### Demo

Screenshot 2024-06-14 at 4 52 55 PM

Screenshot 2024-06-14 at 4 53 00 PM

## Testing Instructions

* compare the about page for this PR and the live site. the numbers in the table, pie chart and time series chart should be the same, just rounded to the nearest 1,000 (MW instead of KW)

### CODE REVIEW

**Comment by vkoves** [comment]
@derekeder - I know we also mentioned making clearer the about page graph legend is really a set of filters, either with a text label or better styling. Did you want to tackle that in this PR as well?

**Comment by vkoves** [comment]
I think the only note is under the graph there's a note that's still in kilowatts

Screenshot from 2024-06-15 14-28-51

Also do you want to also update the reference tables, or keep those the same since it's by county?

**Comment by derekeder** [comment]
@vkoves thx - fixed the additional kilowatt references. I also updated the chart colors to match again across the pie and time series (utility is blue, community solar is orange, etc)

I'll get the reference tables in a separate PR. I have an issue open for it #49

**Review by vkoves — APPROVED** [review]
Looks great to me now!

**Pull request merged**
